Mvvm
IvanchenkoSA/HWAndroid pull request #2
Opened 2023-10-24 19:16 UTC by IvanchenkoSA

2023-10-25 18:47 UTC, jukov requested changes

2023-10-25 18:47 UTC, jukov commented on app/src/main/java/ru/netology/nmedia/activity/MainActivity.kt
> +        viewModel.data.observe(this){post ->
формат

2023-10-25 18:47 UTC, jukov commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryMemoryImpl.kt
> +        }
Попробуй переделать так чтобы copy 1 раз вызывался, а не 2

2023-10-25 18:47 UTC, jukov commented on app/src/main/java/ru/netology/nmedia/supFun/extention.kt
> +    return "$result${if (value in 1100..9999) "." + value.toString()[1] else ""}$appendix"
Убери логику из кавычек, тяжело понимать что тут происходит

2023-10-25 18:48 UTC, jukov commented
С лайвдатами и вьюмоделью главное всё правильно сделал, красава

2023-11-04 07:06 UTC, IvanchenkoSA commented on app/src/main/java/ru/netology/nmedia/activity/MainActivity.kt
> +        viewModel.data.observe(this){post ->
готово

2023-11-04 07:06 UTC, IvanchenkoSA commented on app/src/main/java/ru/netology/nmedia/supFun/extention.kt
> +    return "$result${if (value in 1100..9999) "." + value.toString()[1] else ""}$appendix"
кхм

2023-11-04 07:07 UTC, IvanchenkoSA commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryMemoryImpl.kt
> +        }
переделал

2023-11-04 08:27 UTC, merged